/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39

  Company:
      Microchip Technology, Inc.
 
  File Name:
     GTSU2.h
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef PARROT_H
#define PARROT_H
/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif




/*****************************************************************************
 * This is an error check for the color depth
 *****************************************************************************/
#if (COLOR_DEPTH > 16)
#error "Color Depth needs to be 16 to correctly use these resources"
#endif



/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: parrot_0_0
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_0_0;
#define parrot_0_0_WIDTH     (80)
#define parrot_0_0_HEIGHT    (60)
#define parrot_0_0_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_0_1
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_0_1;
#define parrot_0_1_WIDTH     (80)
#define parrot_0_1_HEIGHT    (60)
#define parrot_0_1_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_0_2
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_0_2;
#define parrot_0_2_WIDTH     (80)
#define parrot_0_2_HEIGHT    (60)
#define parrot_0_2_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_0_3
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_0_3;
#define parrot_0_3_WIDTH     (80)
#define parrot_0_3_HEIGHT    (60)
#define parrot_0_3_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_1_0
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_1_0;
#define parrot_1_0_WIDTH     (80)
#define parrot_1_0_HEIGHT    (60)
#define parrot_1_0_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_1_1
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_1_1;
#define parrot_1_1_WIDTH     (80)
#define parrot_1_1_HEIGHT    (60)
#define parrot_1_1_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_1_2
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_1_2;
#define parrot_1_2_WIDTH     (80)
#define parrot_1_2_HEIGHT    (60)
#define parrot_1_2_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_1_3
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_1_3;
#define parrot_1_3_WIDTH     (80)
#define parrot_1_3_HEIGHT    (60)
#define parrot_1_3_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_2_0
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_2_0;
#define parrot_2_0_WIDTH     (80)
#define parrot_2_0_HEIGHT    (60)
#define parrot_2_0_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_2_1
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_2_1;
#define parrot_2_1_WIDTH     (80)
#define parrot_2_1_HEIGHT    (60)
#define parrot_2_1_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_2_2
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_2_2;
#define parrot_2_2_WIDTH     (80)
#define parrot_2_2_HEIGHT    (60)
#define parrot_2_2_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_2_3
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_2_3;
#define parrot_2_3_WIDTH     (80)
#define parrot_2_3_HEIGHT    (60)
#define parrot_2_3_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_3_0
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_3_0;
#define parrot_3_0_WIDTH     (80)
#define parrot_3_0_HEIGHT    (60)
#define parrot_3_0_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_3_1
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_3_1;
#define parrot_3_1_WIDTH     (80)
#define parrot_3_1_HEIGHT    (60)
#define parrot_3_1_SIZE      (5318)
/*********************************
 * Bitmap Structure
 * Label: parrot_3_2
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR parrot_3_2;
#define parrot_3_2_WIDTH     (80)
#define parrot_3_2_HEIGHT    (60)
#define parrot_3_2_SIZE      (5318)
#endif

