/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39

  Company:
      Microchip Technology, Inc.
 
  File Name:
     GTSU2_reference.c
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif



/*****************************************************************************
 * SECTION:  Graphics Configuration: Bitmap Check
 *****************************************************************************/

#ifdef GFX_CONFIG_IMAGE_FLASH_DISABLE
#error The GFX_CONFIG_IMAGE_FLASH_DISABLE is defined in system_config.h header file.
#endif


/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: parrot_0_0
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_0_0[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_0_0[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_0_0 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_0_0,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_0_1
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_0_1[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_0_1[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_0_1 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_0_1,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_0_2
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_0_2[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_0_2[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_0_2 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_0_2,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_0_3
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_0_3[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_0_3[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_0_3 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_0_3,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_1_0
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_1_0[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_1_0[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_1_0 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_1_0,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_1_1
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_1_1[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_1_1[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_1_1 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_1_1,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_1_2
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_1_2[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_1_2[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_1_2 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_1_2,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_1_3
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_1_3[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_1_3[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_1_3 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_1_3,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_2_0
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_2_0[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_2_0[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_2_0 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_2_0,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_2_1
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_2_1[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_2_1[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_2_1 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_2_1,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_2_2
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_2_2[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_2_2[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_2_2 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_2_2,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_2_3
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_2_3[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_2_3[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_2_3 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_2_3,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_3_0
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_3_0[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_3_0[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_3_0 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_3_0,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_3_1
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_3_1[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_3_1[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_3_1 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_3_1,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: parrot_3_2
 * Description:  80x60 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __parrot_3_2[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __parrot_3_2[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR parrot_3_2 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __parrot_3_2,
    .resource.image.width = 80,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 5316,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

