/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39

  Company:
      Microchip Technology, Inc.
 
  File Name:
     bitmaps.h
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef BITMAPS_H_FILE
#define BITMAPS_H_FILE
/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif




/*****************************************************************************
 * This is an error check for the color depth
 *****************************************************************************/
#if (COLOR_DEPTH > 16)
#error "Color Depth needs to be 16 to correctly use these resources"
#endif



/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: IMG0_1
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG0_1;
#define IMG0_1_WIDTH     (80)
#define IMG0_1_HEIGHT    (60)
#define IMG0_1_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG0_2
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG0_2;
#define IMG0_2_WIDTH     (80)
#define IMG0_2_HEIGHT    (60)
#define IMG0_2_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG0_3
 * Description:  80x59 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG0_3;
#define IMG0_3_WIDTH     (80)
#define IMG0_3_HEIGHT    (59)
#define IMG0_3_SIZE      (9446)
/*********************************
 * Bitmap Structure
 * Label: IMG1_0
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG1_0;
#define IMG1_0_WIDTH     (80)
#define IMG1_0_HEIGHT    (60)
#define IMG1_0_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG1_1
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG1_1;
#define IMG1_1_WIDTH     (80)
#define IMG1_1_HEIGHT    (60)
#define IMG1_1_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG1_2
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG1_2;
#define IMG1_2_WIDTH     (80)
#define IMG1_2_HEIGHT    (60)
#define IMG1_2_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG1_3
 * Description:  80x59 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG1_3;
#define IMG1_3_WIDTH     (80)
#define IMG1_3_HEIGHT    (59)
#define IMG1_3_SIZE      (9446)
/*********************************
 * Bitmap Structure
 * Label: IMG2_0
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG2_0;
#define IMG2_0_WIDTH     (80)
#define IMG2_0_HEIGHT    (60)
#define IMG2_0_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG2_1
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG2_1;
#define IMG2_1_WIDTH     (80)
#define IMG2_1_HEIGHT    (60)
#define IMG2_1_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG2_2
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG2_2;
#define IMG2_2_WIDTH     (80)
#define IMG2_2_HEIGHT    (60)
#define IMG2_2_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG2_3
 * Description:  80x59 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG2_3;
#define IMG2_3_WIDTH     (80)
#define IMG2_3_HEIGHT    (59)
#define IMG2_3_SIZE      (9446)
/*********************************
 * Bitmap Structure
 * Label: IMG3_0
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG3_0;
#define IMG3_0_WIDTH     (80)
#define IMG3_0_HEIGHT    (60)
#define IMG3_0_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG3_1
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG3_1;
#define IMG3_1_WIDTH     (80)
#define IMG3_1_HEIGHT    (60)
#define IMG3_1_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG3_2
 * Description:  80x60 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG3_2;
#define IMG3_2_WIDTH     (80)
#define IMG3_2_HEIGHT    (60)
#define IMG3_2_SIZE      (9606)
/*********************************
 * Bitmap Structure
 * Label: IMG3_3
 * Description:  80x59 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR IMG3_3;
#define IMG3_3_WIDTH     (80)
#define IMG3_3_HEIGHT    (59)
#define IMG3_3_SIZE      (9446)
#endif

